// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxx8D0H2Ou_okq3ZIbHPwRvGmeuDFuz68',
    appId: '1:663661160930:web:0e93c2435a174c9c72b1bb',
    messagingSenderId: '663661160930',
    projectId: 'codelab3-2e9ac',
    authDomain: 'codelab3-2e9ac.firebaseapp.com',
    storageBucket: 'codelab3-2e9ac.appspot.com',
    measurementId: 'G-7ZQ8J53WE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB61bZpnilx6YaRF43z526tOtqmWVWCPHo',
    appId: '1:663661160930:android:436af9f67bdb511e72b1bb',
    messagingSenderId: '663661160930',
    projectId: 'codelab3-2e9ac',
    storageBucket: 'codelab3-2e9ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDatUrZQTA2jPKT5uY_xrQ-FYhSDY96sTY',
    appId: '1:663661160930:ios:69417499c163b1a272b1bb',
    messagingSenderId: '663661160930',
    projectId: 'codelab3-2e9ac',
    storageBucket: 'codelab3-2e9ac.appspot.com',
    iosBundleId: 'com.example.codelab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDatUrZQTA2jPKT5uY_xrQ-FYhSDY96sTY',
    appId: '1:663661160930:ios:69417499c163b1a272b1bb',
    messagingSenderId: '663661160930',
    projectId: 'codelab3-2e9ac',
    storageBucket: 'codelab3-2e9ac.appspot.com',
    iosBundleId: 'com.example.codelab3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxx8D0H2Ou_okq3ZIbHPwRvGmeuDFuz68',
    appId: '1:663661160930:web:d3e4e1d81e82473472b1bb',
    messagingSenderId: '663661160930',
    projectId: 'codelab3-2e9ac',
    authDomain: 'codelab3-2e9ac.firebaseapp.com',
    storageBucket: 'codelab3-2e9ac.appspot.com',
    measurementId: 'G-PZMY27XW65',
  );
}
